[phases.setup]
nixPkgs = ['python310', 'ffmpeg', 'opencv4']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python bot.py'
